# Generated by Django 5.1.7 on 2025-03-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='expression',
            field=models.CharField(max_length=255),
        ),
    ]
